language: python
dist: trusty
python:
  - "3.8"
notifications: 
  email: false
install:
  - pip install -r requirements.txt
  - pip install nose
  - pip install codecov
script: "python -m nose sos4hjb --with-coverage"
after_success:
  - codecov
